### ISSUE TITLE
check-beanstalkd.rb returns a failure 'NOT FOUND' if tube is missing

### ISSUE THREAD

**Issue by Azulinho** [sensu-plugins/sensu-plugins-beanstalk#4]
Currently check-beanstalkd.rb returns a failure 'NOT FOUND' if a particular tube being monitored is missing.
This should be handled gracefully and not as a failure, as its part of the beanstalkd protocol, see: https://github.com/kr/beanstalkd/blob/b7b4a6a14b7e8d096dc8cbc255b23be17a228cbb/doc/protocol.txt#L116:L118

tubes are ephemeral by nature, and it is common to have tubes that only exist during busy periods.

**Comment by majormoses** [comment]
released: https://rubygems.org/gems/sensu-plugins-beanstalk/versions/1.2.0
